baseURL = 'https://charithe.github.io/'
languageCode = 'en-gb'
title = "Cell's notes"

[params]
github = 'charithe'
name = 'Charith Ellawala'


[module]
[[module.imports]]
path = "github.com/nanxiaobei/hugo-paper"
